name: dotnet-ci

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: dotnet-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'

      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release

  test:
    name: dotnet-test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'

      - run: dotnet test --no-build --configuration Release

  sonar:
    name: sonar-quality-gate
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Sonar Begin
        run: |
          dotnet sonarscanner begin \
            /k:"marcelo-mattos_hydrix" \
            /o:"marcelo-mattos" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io"

      - name: Build
        run: dotnet build --configuration Release

      - name: Sonar End
        run: dotnet sonarscanner end \
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
